services:
  postgres:
    image: postgres:17
    container_name: totp-sender-postgres
    environment:
      POSTGRES_DB: totp_sender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
