server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: totp-sender

  datasource:
    url: jdbc:postgresql://localhost:5432/totp_sender
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  security:
    user:
      name: disabled
      password: disabled

logging:
  config: classpath:logback-spring.xml
  level:
    com.example.totpsender: DEBUG
